apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-backend
  template:
    metadata:
      labels:
        app: ml-backend
    spec:
      containers:
      - name: ml-backend
        image: your_dockerhub_username/ml-backend:latest
        ports:
        - containerPort: 5000